export const labelMap = {
    "adultEducation": "Adult Education",
    "budgeting": "Budgeting",
    "childcare": "Child Care",
    "childrensEducation": "Children's Education",
    "clothing": "Clothing",
    "communityInvolvement": "Community Involvement",
    "disabilities": "Disabilities",
    "employment": "Employment",
    "familyServicesAndMentoring": "Family Services and Mentoring",
    "familyFriendsSupport": "Support of Family and Friends",
    "food": "Food",
    "healthInsurance": "Health Insurance",
    "housing": "Housing",
    "internetAccess": "Internet Access",
    "legal": "Legal",
    "lifeSkills": "Life Skills",
    "mentalHealth": "Mental Health",
    "money": "Money",
    "parentingSkills": "Parenting Skills",
    "racismBigotry": "Racism/Bigotry",
    "safety": "Safety",
    "substances": "Drugs/Alcohol",
    "transportation": "Transportation",
    "volunteering": "Volunteering",
}
export const colorMap = {
    "adultEducation": "#ff0000",
    "budgeting": "#ff5900",
    "childcare": "#ff8800",
    "childrensEducation": "#ffc400",
    "clothing": "#eeff00",
    "communityInvolvement": "#99ff00",
    "disabilities": "#2eff00",
    "employment": "#00ff80",
    "familyServicesAndMentoring": "#00ffc4",
    "familyFriendsSupport": "#00d9ff",
    "food": "#00b2ff",
    "healthInsurance": "#008afa",
    "housing": "#0066ff",
    "internetAccess": "#0033ff",
    "legal": "#6500fd",
    "lifeSkills": "#a100ff",
    "mentalHealth": "#ee00ff",
    "money": "#ff0080",
    "parentingSkills": "#7f7f7f",
    "racismBigotry": "#4f4f4f",
    "safety": "#2c2c2c",
    "substances": "#000000",
    "transportation": "#b30000",
    "volunteering": "#67007d",
}
