export const labelMap = {
    "adultEducation": "Adult Education",
    "budgeting": "Budgeting",
    "childcare": "Child Care",
    "childrensEducation": "Children's Education",
    "clothing": "Clothing",
    "communityInvolvement": "Community Involvement",
    "disabilities": "Disabilities",
    "employment": "Employment",
    "familyServicesAndMentoring": "Family Services and Mentoring",
    "familyFriendsSupport": "Support of Family and Friends",
    "food": "Food",
    "healthInsurance": "Health Insurance",
    "housing": "Housing",
    "internetAccess": "Internet Access",
    "legal": "Legal",
    "lifeSkills": "Life Skills",
    "mentalHealth": "Mental Health",
    "money": "Money",
    "parentingSkills": "Parenting Skills",
    "racismBigotry": "Racism/Bigotry",
    "safety": "Safety",
    "substances": "Drugs/Alcohol",
    "transportation": "Transportation",
    "volunteering": "Volunteering",
}
export const colorMap = {
    "adultEducation": ["#ff0000", "#ffffff"],
    "budgeting": ["#ff5900", "#ffffff"],
    "childcare": ["#ff8800", "#ffffff"],
    "childrensEducation": ["#ffc400", "#000000"],
    "clothing": ["#eeff00", "#000000"],
    "communityInvolvement": ["#99ff00", "#000000"],
    "disabilities": ["#2eff00", "#000000"],
    "employment": ["#00ff80", "#000000"],
    "familyServicesAndMentoring": ["#00ffc4", "#000000"],
    "familyFriendsSupport": ["#00d9ff", "#ffffff"],
    "food": ["#00b2ff", "#ffffff"],
    "healthInsurance": ["#008afa", "#ffffff"],
    "housing": ["#0066ff", "#ffffff"],
    "internetAccess": ["#0033ff", "#ffffff"],
    "legal": ["#6500fd", "#ffffff"],
    "lifeSkills": ["#a100ff", "#ffffff"],
    "mentalHealth": ["#ee00ff", "#ffffff"],
    "money": ["#ff0080", "#ffffff"],
    "parentingSkills": ["#7f7f7f", "#ffffff"],
    "racismBigotry": ["#4f4f4f", "#ffffff"],
    "safety": ["#2c2c2c", "#ffffff"],
    "substances": ["#000000", "#ffffff"],
    "transportation": ["#b30000", "#ffffff"],
    "volunteering": ["#67007d", "#ffffff"],
}
