export const labelMap = {
    "adultEducation": "Adult Education",
    "budgeting": "Budgeting",
    "childcare": "Child Care",
    "childrensEducation": "Children's Education",
    "childSupport": "Child Support",
    "clothing": "Clothing",
    "communityInvolvement": "Community Involvement",
    "dental": "Dental",
    "disabilities": "Disabilities",
    "work": "Employment",
    "familyServicesAndMentoring": "Family Services and Mentoring",
    "familyFriendsSupport": "Support of Family and Friends",
    "food": "Food",
    "health": "Health",
    "healthInsurance": "Health Insurance",
    "housing": "Housing",
    "internetAccess": "Internet Access",
    "legal": "Legal",
    "lifeSkills": "Life Skills",
    "mentalHealth": "Mental Health",
    "money": "Money",
    "parentingSkills": "Parenting Skills",
    "racismBigotry": "Racism/Bigotry",
    "safety": "Safety",
    "substances": "Drugs/Alcohol",
    "transportation": "Transportation",
    "volunteering": "Volunteering",
}
